__netbox_{gunicorn,uwsgi}: add state parameter
Adds the --state parameter to both types. With it, the transition
between both types can be done smothly.

diff --git a/type/__netbox_gunicorn/manifest b/type/__netbox_gunicorn/manifest
--- a/type/__netbox_gunicorn/manifest
+++ b/type/__netbox_gunicorn/manifest
@@ -1,23 +1,55 @@
 #!/bin/sh -e
+# __netbox_gunicorn/manifest
 
-HOST=""
-while read -r host; do
-    # shellcheck disable=SC2089
-    HOST="$HOST '$host',"
-done < "$__object/parameter/bind-to"
-# shellcheck disable=SC2090
-export HOST
+# Check states
+state=""
+unit_state=""
+param_state="$(cat "$__object/parameter/state")"
 
-# process template
-mkdir "$__object/files"
-"$__type/files/gunicorn.py.sh" > "$__object/files/gunicorn.py"
+case "$param_state" in
+    enabled|disabled)
+        state="present"
+        unit_state="$param_state"
+        ;;
 
-# gunicorn config file
-__file /opt/netbox/gunicorn.py \
-    --mode 644 --owner netbox \
-    --source "$__object/files/gunicorn.py"
+    absent)
+        state="absent"
+        unit_state="disabled"
+        ;;
+
+    *)
+        # does not exist
+        printf "The state '%s' does not exist, can't continue!\n" "$param_state" >&2
+        exit 2
+        ;;
+esac
+
+
+if [ "$state" = "present" ]; then
+    HOST=""
+    while read -r host; do
+        # shellcheck disable=SC2089
+        HOST="$HOST '$host',"
+    done < "$__object/parameter/bind-to"
+    # shellcheck disable=SC2090
+    export HOST
+
+    # process template
+    mkdir "$__object/files"
+    "$__type/files/gunicorn.py.sh" > "$__object/files/gunicorn.py"
+
+    # gunicorn config file
+    __file /opt/netbox/gunicorn.py \
+        --mode 644 --owner netbox \
+        --source "$__object/files/gunicorn.py"
+
+else
+    # absent config file
+    __file /opt/netbox/gunicorn.py --state absent
+fi
+
 
 # install service file
 __systemd_unit gunicorn-netbox.service \
-    --source "$__type/files/netbox.service" \
-    --enablement-state enabled --restart
+    --state "$state" --enablement-state "$unit_state" \
+    --source "$__type/files/netbox.service" --restart
diff --git a/type/__netbox_uwsgi/manifest b/type/__netbox_uwsgi/manifest
--- a/type/__netbox_uwsgi/manifest
+++ b/type/__netbox_uwsgi/manifest
@@ -1,22 +1,54 @@
 #!/bin/sh -e
+# __netbox_uwsgi/manifest
 
-# *bind* parameters are directly processed in the gen script
-if [ -f "$__object/parameter/serve-static" ]; then
-    STATIC_MAP="yes"
-    export STATIC_MAP
+# Check states
+state=""
+unit_state=""
+param_state="$(cat "$__object/parameter/state")"
+
+case "$param_state" in
+    enabled|disabled)
+        state="present"
+        unit_state="$param_state"
+        ;;
+
+    absent)
+        state="absent"
+        unit_state="disabled"
+        ;;
+
+    *)
+        # does not exist
+        printf "The state '%s' does not exist, can't continue!\n" "$param_state" >&2
+        exit 2
+        ;;
+esac
+
+
+if [ "$state" = "present" ]; then
+    # *bind* parameters are directly processed in the gen script
+    if [ -f "$__object/parameter/serve-static" ]; then
+        STATIC_MAP="yes"
+        export STATIC_MAP
+    fi
+
+    # process template
+    mkdir "$__object/files"
+    "$__type/files/uwsgi.ini.sh" > "$__object/files/uwsgi.ini"
+
+    # uwsgi config file
+    # TODO maybe patching with __key_value cause of .ini ?
+    __file /opt/netbox/uwsgi.ini \
+        --mode 644 --owner netbox \
+        --source "$__object/files/uwsgi.ini"
+
+else
+    # absent config file
+    __file /opt/netbox/uwsgi.ini --state absent
 fi
 
-# process template
-mkdir "$__object/files"
-"$__type/files/uwsgi.ini.sh" > "$__object/files/uwsgi.ini"
-
-# uwsgi config file
-# TODO maybe patching with __key_value cause of .ini ?
-__file /opt/netbox/uwsgi.ini \
-    --mode 644 --owner netbox \
-    --source "$__object/files/uwsgi.ini"
 
 # install service file
 __systemd_unit uwsgi-netbox.service \
-    --source "$__type/files/netbox.service" \
-    --enablement-state enabled --restart
+    --state "$state" --enablement-state "$unit_state" \
+    --source "$__type/files/netbox.service" --restart
