[type/__gnupg_key] Add --ownertrust parameter

diff --git a/type/__gnupg_key/gencode-remote b/type/__gnupg_key/gencode-remote
--- a/type/__gnupg_key/gencode-remote
+++ b/type/__gnupg_key/gencode-remote
@@ -24,6 +24,25 @@ shquot() {
 	EOF
 }
 
+map_ownertrust_s() {
+	# https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gnupg.git;a=blob;f=g10/trustdb.h;hb=gnupg-2.4.1#l28
+	case $1
+	in
+		(undefined)
+			echo 2 ;;
+		(never)
+			echo 3 ;;
+		(marginal)
+			echo 4 ;;
+		(full|fully)
+			echo 5 ;;
+		(ultimate)
+			echo 6 ;;
+		(*)
+			return 1 ;;
+	esac
+}
+
 GNUPGHOME_remote=$(cat "${__object:?}/parameter/homedir")
 if test -f "${__object:?}/parameter/key-id"
 then
@@ -37,27 +56,59 @@ read -r state_should <"${__object:?}/parameter/state"
 case ${state_should}
 in
 	(present)
-		test -f "${__object:?}/files/needs-update" || exit 0
-
-		if test -f "${__object:?}/parameter/source"
+		if test -f "${__object:?}/files/needs-update"
 		then
-			# "manual" source, use uploaded file from code-remote
-			printf 'gpg --homedir %s --batch --no-autostart --import "${__object:?}/files/src.gpg"\n' \
-				"$(shquot "${GNUPGHOME_remote:?}")"
-		else
-			# auto key locate
-			gpgopts=
-			if test -f "${__object:?}/parameter/key-locate-mechanisms"
+			if test -f "${__object:?}/parameter/source"
 			then
-				while read -r _mechanisms
-				do
-					gpgopts="${gpgopts-} --auto-key-locate $(shquot "${_mechanisms}")"
-				done <"${__object:?}/parameter/key-locate-mechanisms"
-				unset -v _mechanisms
-			fi
+				# "manual" source, use uploaded file from code-remote
+				printf 'gpg --homedir %s --batch --no-autostart --import "${__object:?}/files/src.gpg"\n' \
+					"$(shquot "${GNUPGHOME_remote:?}")"
+			else
+				# auto key locate
+				gpgopts=
+				if test -f "${__object:?}/parameter/key-locate-mechanisms"
+				then
+					while read -r _mechanisms
+					do
+						gpgopts="${gpgopts-} --auto-key-locate $(shquot "${_mechanisms}")"
+					done <"${__object:?}/parameter/key-locate-mechanisms"
+					unset -v _mechanisms
+				fi
 
-			printf 'gpg --homedir %s%s --batch --locate-external-keys %s\n' \
-				"$(shquot "${GNUPGHOME_remote:?}")" "${gpgopts}" "$(shquot "${keyid}")"
+				printf 'gpg --homedir %s%s --batch --locate-external-keys %s\n' \
+					"$(shquot "${GNUPGHOME_remote:?}")" "${gpgopts}" \
+					"$(shquot "${keyid}")"
+			fi
+		fi
+
+		if test -f "${__object:?}/parameter/ownertrust"
+		then
+			read -r ownertrust_is <"${__object:?}/explorer/ownertrust" || :
+			read -r ownertrust_should_s <"${__object:?}/parameter/ownertrust"
+
+			ownertrust_should=$(map_ownertrust_s "${ownertrust_should_s}") || {
+				printf 'Invalid --ownertrust: %s\n' "${ownertrust_should_s-}" >&2
+				exit 1
+			}
+
+			if test "${ownertrust_is}" != "${ownertrust_should}"
+			then
+				# update ownertrust
+				case ${#keyid}
+				in
+					(40)
+						;;
+					(*)
+						printf 'key ID must be a fingerprint to set ownertrust' >&2
+						exit 1
+						;;
+				esac
+
+				printf "echo '%s:%u:' | gpg --homedir %s --batch --import-ownertrust\n" \
+					"${keyid}" \
+					$((ownertrust_should)) \
+					"$(shquot "${GNUPGHOME_remote:?}")"
+			fi
 		fi
 		;;
 	(absent)
