Balance case label parentheses

diff --git a/type/__nginx_vhost/manifest b/type/__nginx_vhost/manifest
--- a/type/__nginx_vhost/manifest
+++ b/type/__nginx_vhost/manifest
@@ -24,7 +24,7 @@ mkdir -p "${__object:?}/files"
 
 case ${os}
 in
-	alpine)
+	(alpine)
 		__package nginx
 
 		nginx_confdir="/etc/nginx"
@@ -38,7 +38,7 @@ in
 		export NGINX_WEBROOT="/var/www"
 		export ACME_CHALLENGE_DIR="${NGINX_WEBROOT}/.well-known/acme-challenge/"
 		;;
-	debian|ubuntu)
+	(debian|ubuntu)
 		__package nginx
 
 		nginx_confdir="/etc/nginx"
@@ -50,9 +50,10 @@ in
 		export NGINX_WEBROOT="/var/www"
 		export ACME_CHALLENGE_DIR="${NGINX_WEBROOT}/.well-known/acme-challenge/"
 		;;
-	*)
-		echo "This type does not support ${os} yet. Aborting." >&2;
-		exit 1;
+	(*)
+		echo "This type does not support ${os} yet. Aborting." >&2
+		exit 1
+		;;
 esac
 
 # Domain
diff --git a/type/__uacme_obtain/gencode-remote b/type/__uacme_obtain/gencode-remote
--- a/type/__uacme_obtain/gencode-remote
+++ b/type/__uacme_obtain/gencode-remote
@@ -24,13 +24,13 @@
 os=$(cat "${__global:?}"/explorer/os)
 case ${os}
 in
-	alpine|ubuntu|debian)
+	(alpine|ubuntu|debian)
 		default_confdir=/etc/ssl/uacme
-	;;
-	*)
-		echo "__uacme_obtain currently has no implementation for ${os}. Aborting." >&2;
-		exit 1;
-	;;
+		;;
+	(*)
+		echo "__uacme_obtain currently has no implementation for ${os}. Aborting." >&2
+		exit 1
+		;;
 esac
 
 confdir="${default_confdir:?}"
diff --git a/type/__wikijs/manifest b/type/__wikijs/manifest
--- a/type/__wikijs/manifest
+++ b/type/__wikijs/manifest
@@ -23,12 +23,12 @@ os=$(cat "${__global:?}"/explorer/os)
 
 case ${os}
 in
-	alpine)
-		:
+	(alpine)
 		;;
-	*)
-		echo "This type has no implementation for ${os}. Aborting." >&2;
-		exit 1;
+	(*)
+		echo "This type has no implementation for ${os}. Aborting." >&2
+		exit 1
+		;;
 esac
 
 DB_USER=wikijs
