[type/*opam*] Always check for existence of opam root prior to running opam(1)
If the given opam root does not exist when calling opam(1), it will create a
lock file in the given directory, preventing creation of said root later on
because opam-init(1) will only create a root if the root directory does not
exist or is empty.

diff --git a/type/__opam_root/explorer/root-dir b/type/__opam_root/explorer/root-dir
--- a/type/__opam_root/explorer/root-dir
+++ b/type/__opam_root/explorer/root-dir
@@ -30,8 +30,16 @@ else
 	if test -s "${__object:?}/parameter/user"
 	then
 		read -r user <"${__object:?}/parameter/user"
-	else
+	elif test "${__object_name:?}" != "${__object_name#__opam_root/}"
+	then
+		# only fall back to __object_id if this explorer is called from an
+		# __opam_root object since this explorer is linked to
+		# type/__opam_switch, type/__opam_pin and type/__package_opam, too,
+		# where __object_id has a different meaning.
 		user=${__object_id:?}
+	else
+		echo 'cannot determine OPAM user.' >&2
+		exit 1
 	fi
 
 	home_dir=$(
@@ -41,7 +49,7 @@ else
 		else
 			awk -F ':' -v user="${user}" '$1==user'
 		fi \
-			| cut -d ':' -f 6)
+		| cut -d ':' -f 6)
 
 	test -n "${home_dir}" || home_dir=$(eval "cd ~${user} && pwd -P")
 
diff --git a/type/__package_opam/explorer/depexts b/type/__package_opam/explorer/depexts
--- a/type/__package_opam/explorer/depexts
+++ b/type/__package_opam/explorer/depexts
@@ -27,24 +27,34 @@ if test -f "${__object:?}/parameter/no-depexts"
 then
 	exit 0
 fi
-if ! command -v opam >/dev/null 2>&1
-then
-	# cannot determine depexts
-	echo '?'
-	exit 0
-fi
 
 opam_vars='OPAMUTF8=never OPAMCOLOR=never OPAMROOTISOK=1 OPAMSTATUSLINE=never OPAMCLI=2.0'
-if test -s "${__object:?}/parameter/root"
-then
-	OPAMROOT=$(cat "${__object:?}/parameter/root")
-	opam_vars="${opam_vars} OPAMROOT=$(quote "${OPAMROOT}")"
-fi
+
+OPAMROOT=$("${__type_explorer:?}/root-dir")
+opam_vars="${opam_vars} OPAMROOT=$(quote "${OPAMROOT}")"
+
 if test -s "${__object:?}/parameter/switch"
 then
 	read -r OPAMSWITCH <"${__object:?}/parameter/switch"
 	opam_vars="${opam_vars} OPAMSWITCH=$(quote "${OPAMSWITCH}")"
 fi
+
+# shellcheck disable=SC2015
+command -v opam >/dev/null 2>&1 \
+&& {
+	# NOTE: check for presence of opam root always before executing opam(1) as
+	#       opam will create a lock file inside the $OPAMROOT even if it is not
+	#       a valid root, thus preventing creation of said root later on.
+	# cf. type/__opam_root/explorer/state
+	test -e "${OPAMROOT}/config" || test -e "${OPAMROOT}/aliases"
+} || {
+	# cannot determine depexts if the opam root hasn’t been created, yet.
+
+	# FIXME: this likely results in a build fail because of missing
+	#        dependencies.
+	echo '?'
+	exit 0
+}
 
 read -r user <"${__object:?}/parameter/user"
 
