Put braces around parameter expansions
Fixes SC2250: Prefer putting braces around variable references even when not strictly required.

diff --git a/type/__borg_repo/gencode-remote b/type/__borg_repo/gencode-remote
--- a/type/__borg_repo/gencode-remote
+++ b/type/__borg_repo/gencode-remote
@@ -36,7 +36,7 @@ case "$(cat "${__object:?}/parameter/encryption")" in
 		fi
 		;;
 	*)
-		echo "$enc is not a known encryption mode for __borg_repo. Aborting." >&2
+		echo "${enc} is not a known encryption mode for __borg_repo. Aborting." >&2
 		exit 1;
 esac
 
@@ -53,6 +53,6 @@ fi
 cat <<- EOF
 	set -x
 	if [ ! -d "/${__object_id:?}" ]; then
-		$doas BORG_NEW_PASSPHRASE=$passphrase borg init -e ${enc:?} $appendonly /${__object_id:?}
+		${doas} BORG_NEW_PASSPHRASE=${passphrase} borg init -e ${enc:?} ${appendonly} /${__object_id:?}
 	fi
 EOF
diff --git a/type/__borg_repo/manifest b/type/__borg_repo/manifest
--- a/type/__borg_repo/manifest
+++ b/type/__borg_repo/manifest
@@ -20,16 +20,16 @@
 
 os=$(cat "${__global:?}"/explorer/os)
 
-case "$os" in
+case "${os}" in
 	"alpine")
 		borg_package=borgbackup
 		;;
 	*)
-		echo "__borg_repo is not yet implemented for os $os. Aborting." >&2;
+		echo "__borg_repo is not yet implemented for os ${os}. Aborting." >&2;
 		exit 1;
 esac
 
-__package "$borg_package"
+__package "${borg_package}"
 
 if [ -f "${__object:?}/parameter/owner" ];
 then
diff --git a/type/__jitsi_meet_user/manifest b/type/__jitsi_meet_user/manifest
--- a/type/__jitsi_meet_user/manifest
+++ b/type/__jitsi_meet_user/manifest
@@ -23,18 +23,17 @@ basic_urlencode() {
   echo "${1}" | sed 's/\./%2e/g' | sed 's/-/%2d/g' | sed 's/_/%5f/g'
 }
 
-PASSWD=$(cat "${__object}/parameter/password" 2>/dev/null || true)
-STATE=$(cat "${__object}/parameter/state")
+PASSWD=$(cat "${__object:?}/parameter/password" 2>/dev/null || true)
+STATE=$(cat "${__object:?}/parameter/state")
 
 if [ -z "${PASSWD}" ] && [ "${STATE}" != "absent" ]; then
-	cat >> dev/stderr <<-EOF
-	A password is required unless you are removing the user '$__object_id'.
-	EOF
+  printf "A password is required unless you are removing the user '%s'.\n" >&2 \
+    "${__object_id:?}"
 fi
 
-JITSI_USER_RAW=${__object_id}
+JITSI_USER_RAW=${__object_id:?}
 if echo "${JITSI_USER_RAW}" | grep -q ".*[A-Z\"&'/:<>@]"; then
-  cat > /dev/stderr <<EOF
+  cat >&2 <<EOF
 Username (XMPP's localpart) ${JITSI_USER_RAW} has uppercase characters or
 contains invalid symbols ("&'/:<>@) according to RFC6122.
 EOF
@@ -42,7 +41,7 @@ EOF
 fi
 
 JITSI_USER=$(basic_urlencode "${JITSI_USER_RAW}")
-FQDN=$(basic_urlencode "${__target_host}")
+FQDN=$(basic_urlencode "${__target_host:?}")
 FQDN_PATH="/var/lib/prosody/${FQDN}/accounts"
 FILENAME="${FQDN_PATH}/${JITSI_USER}.dat"
 
diff --git a/type/__netbox_gunicorn/manifest b/type/__netbox_gunicorn/manifest
--- a/type/__netbox_gunicorn/manifest
+++ b/type/__netbox_gunicorn/manifest
@@ -21,12 +21,12 @@
 # Check states
 state=""
 unit_state=""
-param_state=$(cat "$__object/parameter/state")
+param_state=$(cat "${__object:?}/parameter/state")
 
-case "$param_state" in
+case "${param_state}" in
     enabled|disabled)
         state="present"
-        unit_state=$param_state
+        unit_state=${param_state}
         ;;
 
     absent)
@@ -36,22 +36,22 @@ case "$param_state" in
 
     *)
         # does not exist
-        printf "The state '%s' does not exist, can't continue!\n" "$param_state" >&2
+        printf "The state '%s' does not exist, can't continue!\n" "${param_state}" >&2
         exit 2
         ;;
 esac
 
 
-mkdir "$__object/files"
+mkdir "${__object:?}/files"
 
-if [ "$state" = "present" ]; then
+if [ "${state}" = "present" ]; then
     # process template
-    "$__type/files/gunicorn.py.sh" > "$__object/files/gunicorn.py"
+    "${__type:?}/files/gunicorn.py.sh" > "${__object:?}/files/gunicorn.py"
 
     # gunicorn config file
     __file /opt/netbox/gunicorn.py \
         --mode 644 --owner netbox \
-        --source "$__object/files/gunicorn.py"
+        --source "${__object:?}/files/gunicorn.py"
 
 else
     # absent config file
@@ -62,13 +62,13 @@ fi
 TYPE="Gunicorn"
 export TYPE
 
-"$__type/files/netbox.socket.sh" "$__object/parameter/bind-to" \
-    > "$__object/files/netbox.socket"
+"${__type:?}/files/netbox.socket.sh" "${__object:?}/parameter/bind-to" \
+    > "${__object:?}/files/netbox.socket"
 
 # install systemd files
 __systemd_unit gunicorn-netbox.socket \
-    --state "$state" --enablement-state "$unit_state" \
-    --source "$__object/files/netbox.socket" --restart
+    --state "${state}" --enablement-state "${unit_state}" \
+    --source "${__object:?}/files/netbox.socket" --restart
 __systemd_unit gunicorn-netbox.service \
-    --state "$state" --enablement-state "$unit_state" \
-    --source "$__type/files/netbox.service" --restart
+    --state "${state}" --enablement-state "${unit_state}" \
+    --source "${__type:?}/files/netbox.service" --restart
diff --git a/type/__netbox_uwsgi/manifest b/type/__netbox_uwsgi/manifest
--- a/type/__netbox_uwsgi/manifest
+++ b/type/__netbox_uwsgi/manifest
@@ -21,12 +21,12 @@
 # Check states
 state=""
 unit_state=""
-param_state=$(cat "$__object/parameter/state")
+param_state=$(cat "${__object:?}/parameter/state")
 
-case "$param_state" in
+case "${param_state}" in
     enabled|disabled)
         state="present"
-        unit_state=$param_state
+        unit_state=${param_state}
         ;;
 
     absent)
@@ -36,43 +36,43 @@ case "$param_state" in
 
     *)
         # does not exist
-        printf "The state '%s' does not exist, can't continue!\n" "$param_state" >&2
+        printf "The state '%s' does not exist, can't continue!\n" "${param_state}" >&2
         exit 2
         ;;
 esac
 
 
-mkdir "$__object/files"
+mkdir "${__object:?}/files"
 
 # check if systemd sockets will be used
-if [ -f "$__object/parameter/bind-to" ]; then
+if [ -f "${__object:?}/parameter/bind-to" ]; then
     SYSTEMD_SOCKET="yes"
 fi
-if find "$__object/parameter/" -maxdepth 1 -name "*-bind" -print -quit | grep -q .; then
+if find "${__object:?}/parameter/" -maxdepth 1 -name "*-bind" -print -quit | grep -q .; then
     SYSTEMD_SOCKET="no"
 fi
-echo "$SYSTEMD_SOCKET" > "$__object/files/systemd_socket"
+echo "${SYSTEMD_SOCKET}" > "${__object:?}/files/systemd_socket"
 
-if [ "$state" = "present" ]; then
+if [ "${state}" = "present" ]; then
     # already checked outside this if-clause
     export SYSTEMD_SOCKET
 
-    PROTOCOL=$(cat "$__object/parameter/protocol")
+    PROTOCOL=$(cat "${__object:?}/parameter/protocol")
     export PROTOCOL
 
-    if [ -f "$__object/parameter/serve-static" ]; then
+    if [ -f "${__object:?}/parameter/serve-static" ]; then
         STATIC_MAP="yes"
         export STATIC_MAP
     fi
 
     # process template
-    "$__type/files/uwsgi.ini.sh" > "$__object/files/uwsgi.ini"
+    "${__type:?}/files/uwsgi.ini.sh" > "${__object:?}/files/uwsgi.ini"
 
     # uwsgi config file
     # TODO maybe patching with __key_value cause of .ini ?
     __file /opt/netbox/uwsgi.ini \
         --mode 644 --owner netbox \
-        --source "$__object/files/uwsgi.ini"
+        --source "${__object:?}/files/uwsgi.ini"
 
 else
     # absent config file
@@ -81,23 +81,23 @@ fi
 
 
 # handle the systemd socket
-if [ "$SYSTEMD_SOCKET" = "yes" ]; then
+if [ "${SYSTEMD_SOCKET}" = "yes" ]; then
     TYPE="uWSGI"
     export TYPE
 
     # generate and set the socket unit
-    "$__type/files/netbox.socket.sh" "$__object/parameter/bind-to" \
-        > "$__object/files/netbox.socket"
+    "${__type:?}/files/netbox.socket.sh" "${__object:?}/parameter/bind-to" \
+        > "${__object:?}/files/netbox.socket"
     __systemd_unit uwsgi-netbox.socket \
-        --state "$state" --enablement-state "$unit_state" \
-        --source "$__object/files/netbox.socket" --restart
+        --state "${state}" --enablement-state "${unit_state}" \
+        --source "${__object:?}/files/netbox.socket" --restart
 else
     # remove the systemd socket unit
     __systemd_unit uwsgi-netbox.socket --state absent
 fi
 
 # install service file
-"$__type/files/netbox.service.sh" > "$__object/files/netbox.service"
+"${__type:?}/files/netbox.service.sh" > "${__object:?}/files/netbox.service"
 __systemd_unit uwsgi-netbox.service \
-    --state "$state" --enablement-state "$unit_state" \
-    --source "$__object/files/netbox.service" --restart
+    --state "${state}" --enablement-state "${unit_state}" \
+    --source "${__object:?}/files/netbox.service" --restart
diff --git a/type/__nginx/manifest b/type/__nginx/manifest
--- a/type/__nginx/manifest
+++ b/type/__nginx/manifest
@@ -19,7 +19,7 @@
 #
 
 os=$(cat "${__global:?}"/explorer/os)
-case "$os" in
+case "${os}" in
 	alpine)
 		nginx_user=nginx
 		nginx_certdir=/etc/nginx/ssl
@@ -29,7 +29,7 @@ case "$os" in
 		nginx_certdir=/etc/nginx/ssl
 		;;
 	*)
-		echo "This type does not support $os yet. Aborting." >&2;
+		echo "This type does not support ${os} yet. Aborting." >&2;
 		exit 1;
 		;;
 esac
@@ -51,28 +51,28 @@ set_custom_uacme_hookscript=
 if [ -f "${__object:?}/parameter/uacme-hookscript" ];
 then
 	uacme_hookscript=$(cat "${__object:?}/parameter/uacme-hookscript")
-	set_custom_uacme_hookscript="--hookscript $uacme_hookscript"
+	set_custom_uacme_hookscript="--hookscript ${uacme_hookscript}"
 fi
 
 # Deploy simple HTTP vhost, allowing to serve ACME challenges.
-__nginx_vhost "301-to-https-$domain" \
-	--domain "$domain" --altdomains "$altdomains" --to-https
+__nginx_vhost "301-to-https-${domain}" \
+	--domain "${domain}" --altdomains "${altdomains}" --to-https
 
 # Obtaining TLS cert.
-cert_ownership=$nginx_user
+cert_ownership=${nginx_user}
 if [ -f "${__object:?}/parameter/force-cert-ownership-to" ]; then
 	cert_ownership=$(cat "${__object:?}/parameter/force-cert-ownership-to")
 fi
 
 __uacme_account
 # shellcheck disable=SC2086
-require="__nginx_vhost/301-to-https-$domain __uacme_account" \
-	__uacme_obtain "$domain" \
-		--altdomains "$altdomains" \
-		$set_custom_uacme_hookscript \
-		--owner "$cert_ownership" \
-		--install-key-to "$nginx_certdir/$domain/privkey.pem" \
-		--install-cert-to "/$nginx_certdir/$domain/fullchain.pem" \
+require="__nginx_vhost/301-to-https-${domain} __uacme_account" \
+	__uacme_obtain "${domain}" \
+		--altdomains "${altdomains}" \
+		${set_custom_uacme_hookscript} \
+		--owner "${cert_ownership}" \
+		--install-key-to "${nginx_certdir}/${domain}/privkey.pem" \
+		--install-cert-to "/${nginx_certdir}/${domain}/fullchain.pem" \
 		--renew-hook "service nginx reload"
 
 # Deploy HTTPS nginx vhost.
@@ -84,11 +84,11 @@ if [ -f "${__object:?}/parameter/config" ]; then
 	fi
 
 	mkdir -p "${__object:?}/files"
-	cat "$nginx_logic" > "${__object:?}/files/config"
+	cat "${nginx_logic}" > "${__object:?}/files/config"
 
-	require="__uacme_obtain/$domain" __nginx_vhost "$domain" \
-		--altdomains "$altdomains" --config "${__object:?}/files/config"
+	require="__uacme_obtain/${domain}" __nginx_vhost "${domain}" \
+		--altdomains "${altdomains}" --config "${__object:?}/files/config"
 else
-	require="__uacme_obtain/$domain" __nginx_vhost "$domain" \
-		--altdomains "$altdomains"
+	require="__uacme_obtain/${domain}" __nginx_vhost "${domain}" \
+		--altdomains "${altdomains}"
 fi
diff --git a/type/__nginx_vhost/manifest b/type/__nginx_vhost/manifest
--- a/type/__nginx_vhost/manifest
+++ b/type/__nginx_vhost/manifest
@@ -22,20 +22,20 @@
 os=$(cat "${__global:?}"/explorer/os)
 mkdir -p "${__object:?}/files"
 
-case "$os" in
+case "${os}" in
 	alpine)
 		__package nginx
 
 		nginx_confdir="/etc/nginx"
 		install_reqs="__package/nginx"
 
-		require=$install_reqs __start_on_boot nginx
+		require=${install_reqs} __start_on_boot nginx
 
-		export NGINX_SITEDIR="$nginx_confdir/conf.d"
-		export NGINX_CERTDIR="$nginx_confdir/ssl"
-		export NGINX_SNIPPETSDIR="$nginx_confdir/snippets"
+		export NGINX_SITEDIR="${nginx_confdir}/conf.d"
+		export NGINX_CERTDIR="${nginx_confdir}/ssl"
+		export NGINX_SNIPPETSDIR="${nginx_confdir}/snippets"
 		export NGINX_WEBROOT="/var/www"
-		export ACME_CHALLENGE_DIR="$NGINX_WEBROOT/.well-known/acme-challenge/"
+		export ACME_CHALLENGE_DIR="${NGINX_WEBROOT}/.well-known/acme-challenge/"
 		;;
 	debian|ubuntu)
 		__package nginx
@@ -43,14 +43,14 @@ case "$os" in
 		nginx_confdir="/etc/nginx"
 		install_reqs="__package/nginx"
 
-		export NGINX_SITEDIR="$nginx_confdir/sites-enabled"
-		export NGINX_CERTDIR="$nginx_confdir/ssl"
-		export NGINX_SNIPPETSDIR="$nginx_confdir/snippets"
+		export NGINX_SITEDIR="${nginx_confdir}/sites-enabled"
+		export NGINX_CERTDIR="${nginx_confdir}/ssl"
+		export NGINX_SNIPPETSDIR="${nginx_confdir}/snippets"
 		export NGINX_WEBROOT="/var/www"
-		export ACME_CHALLENGE_DIR="$NGINX_WEBROOT/.well-known/acme-challenge/"
+		export ACME_CHALLENGE_DIR="${NGINX_WEBROOT}/.well-known/acme-challenge/"
 		;;
 	*)
-		echo "This type does not support $os yet. Aborting." >&2;
+		echo "This type does not support ${os} yet. Aborting." >&2;
 		exit 1;
 esac
 
@@ -74,7 +74,7 @@ export ALTDOMAINS
 if [ -f "${__object:?}/parameter/no-tls" ];
 then
 	TLS=
-	echo "WARNING: you have disabled TLS for vhost $DOMAIN" >&2
+	echo "WARNING: you have disabled TLS for vhost ${DOMAIN}" >&2
 else
 	TLS=ssl
 fi
@@ -103,7 +103,7 @@ if [ -f "${__object:?}/parameter/lport" ];
 then
 	LPORT=$(cat "${__object:?}/parameter/lport")
 else
-	if [ -n "$TLS" ] && [ -z "$TO_HTTPS" ];
+	if [ -n "${TLS}" ] && [ -z "${TO_HTTPS}" ];
 	then
 		LPORT=443
 	else
@@ -113,7 +113,7 @@ fi
 export LPORT
 
 # Server definition
-if [ -n "$TO_HTTPS" ];
+if [ -n "${TO_HTTPS}" ];
 then
 	# Ignore configuration, simply serve ACME challenge and redirect to HTTPS.
 	"${__type:?}/files/to-https.conf.sh" > "${__object:?}/files/vhost.conf"
@@ -130,9 +130,9 @@ then
 
 	# Either use config as-in or template it in generic vhost structure.
 	if [ -f "${__object:?}/parameter/standalone-config" ]; then
-		vhost_conf=$vhost_partial
+		vhost_conf=${vhost_partial}
 	else
-		NGINX_LOGIC=$(cat "$vhost_partial") "${__type:?}/files/generic.conf.sh" \
+		NGINX_LOGIC=$(cat "${vhost_partial}") "${__type:?}/files/generic.conf.sh" \
 			> "${__object:?}/files/vhost.conf"
 
 		vhost_conf="${__object:?}/files/vhost.conf"
@@ -142,21 +142,21 @@ else
 	"${__type:?}/files/static.conf.sh" > "${__object:?}/files/vhost.conf"
 	vhost_conf="${__object:?}/files/vhost.conf"
 
-	require=$install_reqs __directory "$NGINX_WEBROOT/$DOMAIN"
-	require="__directory$NGINX_WEBROOT/$DOMAIN" \
-		__file "$NGINX_WEBROOT/$DOMAIN/index.html" --state exists \
+	require=${install_reqs} __directory "${NGINX_WEBROOT}/${DOMAIN}"
+	require="__directory${NGINX_WEBROOT}/${DOMAIN}" \
+		__file "${NGINX_WEBROOT}/${DOMAIN}/index.html" --state exists \
 		--source "${__type:?}/files/index.html" \
 		--mode 0644
 fi
 
 # Install snippets.
-require=$install_reqs __directory "$NGINX_SNIPPETSDIR"
+require=${install_reqs} __directory "${NGINX_SNIPPETSDIR}"
 for snippet in hsts 301-to-https; do
-	require="__directory/$NGINX_SNIPPETSDIR" __file \
-		"$NGINX_SNIPPETSDIR/$snippet" --source "${__type:?}/files/$snippet"
+	require="__directory/${NGINX_SNIPPETSDIR}" __file \
+		"${NGINX_SNIPPETSDIR}/${snippet}" --source "${__type:?}/files/${snippet}"
 done
 
 # Install vhost.
-require=$install_reqs __file "$NGINX_SITEDIR/$__object_id.conf" \
-	--source "$vhost_conf" \
+require=${install_reqs} __file "${NGINX_SITEDIR}/${__object_id:?}.conf" \
+	--source "${vhost_conf}" \
 	--mode 0644
diff --git a/type/__uacme_account/gencode-remote b/type/__uacme_account/gencode-remote
--- a/type/__uacme_account/gencode-remote
+++ b/type/__uacme_account/gencode-remote
@@ -20,12 +20,12 @@
 
 os=$(cat "${__global:?}"/explorer/os)
 
-case "$os" in
+case "${os}" in
 	alpine|ubuntu|debian)
 		default_confdir=/etc/ssl/uacme
 		;;
 	*)
-		echo "This type currently has no implementation for $os. Aborting." >&2;
+		echo "This type currently has no implementation for ${os}. Aborting." >&2;
 		exit 1
 		;;
 esac
diff --git a/type/__uacme_account/manifest b/type/__uacme_account/manifest
--- a/type/__uacme_account/manifest
+++ b/type/__uacme_account/manifest
@@ -21,13 +21,13 @@
 
 os=$(cat "${__global:?}"/explorer/os)
 
-case "$os" in
+case "${os}" in
 	"alpine"|"debian"|"ubuntu")
 		uacme_package=uacme
 		;;
 	*)
-		echo "__uacme_account is not yet implemented for os $os. Aborting." >&2;
+		echo "__uacme_account is not yet implemented for os ${os}. Aborting." >&2;
 		exit 1;
 esac
 
-__package $uacme_package
+__package ${uacme_package}
diff --git a/type/__uacme_obtain/gencode-remote b/type/__uacme_obtain/gencode-remote
--- a/type/__uacme_obtain/gencode-remote
+++ b/type/__uacme_obtain/gencode-remote
@@ -22,12 +22,12 @@
 # FIXME: this code is duplicated from the manifest -> let's share it somehow.
 
 os=$(cat "${__global:?}"/explorer/os)
-case "$os" in
+case "${os}" in
 	alpine|ubuntu|debian)
 		default_confdir=/etc/ssl/uacme
 	;;
 	*)
-		echo "__uacme_obtain currently has no implementation for $os. Aborting." >&2;
+		echo "__uacme_obtain currently has no implementation for ${os}. Aborting." >&2;
 		exit 1;
 	;;
 esac
@@ -40,4 +40,4 @@ fi
 
 # Run renew script 'by hand' for intial issue - renews will be handled by the
 # cronjob.
-echo "$confdir/${__object_id:?}/renew.sh"
+echo "${confdir}/${__object_id:?}/renew.sh"
diff --git a/type/__uacme_obtain/manifest b/type/__uacme_obtain/manifest
--- a/type/__uacme_obtain/manifest
+++ b/type/__uacme_obtain/manifest
@@ -20,7 +20,7 @@
 #
 
 os=$(cat "${__global:?}"/explorer/os)
-case "$os" in
+case "${os}" in
 	alpine|ubuntu|debian)
 		__package uacme
 
@@ -29,7 +29,7 @@ case "$os" in
 		default_confdir=/etc/ssl/uacme
 	;;
 	*)
-		echo "__uacme_obtain currently has no implementation for $os. Aborting." >&2;
+		echo "__uacme_obtain currently has no implementation for ${os}. Aborting." >&2;
 		exit 1;
 	;;
 esac
@@ -56,13 +56,13 @@ fi
 export DISABLE_OCSP
 
 MAIN_DOMAIN=${__object_id:?}
-DOMAIN=$MAIN_DOMAIN
+DOMAIN=${MAIN_DOMAIN}
 if [ -f "${__object:?}/parameter/altdomains" ];
 then
 	# shellcheck disable=SC2013
 	for altdomain in $(cat "${__object:?}/parameter/altdomains");
 	do
-		DOMAIN="$DOMAIN $altdomain"
+		DOMAIN="${DOMAIN} ${altdomain}"
 	done
 fi
 export MAIN_DOMAIN DOMAIN
@@ -116,25 +116,25 @@ then
 fi
 export RENEW_HOOK
 
-if [ -n "$KEY_TARGET" ] && [ -z "$CERT_TARGET" ]; then
+if [ -n "${KEY_TARGET}" ] && [ -z "${CERT_TARGET}" ]; then
 	echo "You cannot specify --install-key-to without --install-cert-to." >&2
 	exit 1
-elif [ -z "$KEY_TARGET" ] && [ -n "$CERT_TARGET" ]; then
+elif [ -z "${KEY_TARGET}" ] && [ -n "${CERT_TARGET}" ]; then
 	echo "You cannot specify --install-cert-to without --install-key-to." >&2
 	exit 1
 fi
 
 # Make sure challengedir exist.
-__directory "$CHALLENGEDIR" --parents
+__directory "${CHALLENGEDIR}" --parents
 
 # Generate and deploy renew script.
 mkdir -p "${__object:?}/files"
 "${__type:?}/files/renew.sh.sh" > "${__object:?}/files/uacme-renew.sh"
 
-__directory "$CONFDIR/$MAIN_DOMAIN"
-require="__directory/$CONFDIR/$MAIN_DOMAIN" __file "$CONFDIR/$MAIN_DOMAIN/renew.sh" \
+__directory "${CONFDIR}/${MAIN_DOMAIN}"
+require="__directory/${CONFDIR}/${MAIN_DOMAIN}" __file "${CONFDIR}/${MAIN_DOMAIN}/renew.sh" \
 	--mode 0755 --source "${__object:?}/files/uacme-renew.sh"
 
 # Set up renew cronjob - initial issue done in gencode-remote.
-__cron "uacme-$MAIN_DOMAIN" --user root --hour 2 --minute 0 \
-	--command "$CONFDIR/$MAIN_DOMAIN/renew.sh"
+__cron "uacme-${MAIN_DOMAIN}" --user root --hour 2 --minute 0 \
+	--command "${CONFDIR}/${MAIN_DOMAIN}/renew.sh"
diff --git a/type/__wikijs/manifest b/type/__wikijs/manifest
--- a/type/__wikijs/manifest
+++ b/type/__wikijs/manifest
@@ -21,12 +21,12 @@
 
 os=$(cat "${__global:?}"/explorer/os)
 
-case "$os" in
+case "${os}" in
 	alpine)
 		:
 		;;
 	*)
-		echo "This type has no implementation for $os. Aborting." >&2;
+		echo "This type has no implementation for ${os}. Aborting." >&2;
 		exit 1;
 esac
 
@@ -51,7 +51,7 @@ then
 fi
 export SSL
 
-if [ "$SSL" = "true" ];
+if [ "${SSL}" = "true" ];
 then
 	if [ -f "${__object:?}/parameter/letsencrypt-mail" ];
 	then
@@ -79,11 +79,11 @@ __file /etc/init.d/wikijs \
 	--mode 0755
 __package nghttp2-dev  # Required for some reason, else a symbol is missing
 for logfile in wikijs.log wikijs.err; do
-	require="__user/wikijs" __file /var/log/$logfile --owner wikijs
+	require="__user/wikijs" __file /var/log/${logfile} --owner wikijs
 done
 
 mkdir -p "${__object:?}/files"
-"${__type:?}/files/config.yml.sh" "$db_pass" > "${__object:?}/files/config.yml"
+"${__type:?}/files/config.yml.sh" "${db_pass}" > "${__object:?}/files/config.yml"
 require='__user/wikijs' \
 	__file /var/wiki/config.yml \
 	--source "${__object:?}/files/config.yml" \
diff --git a/type/__wireguard/manifest b/type/__wireguard/manifest
--- a/type/__wireguard/manifest
+++ b/type/__wireguard/manifest
@@ -20,12 +20,12 @@
 
 os=$(cat "${__global:?}"/explorer/os)
 
-case $os in
+case ${os} in
 	'alpine')
 		:
 		;;
 	*)
-		echo "This type has no implementation for $os. Aborting." >&2
+		echo "This type has no implementation for ${os}. Aborting." >&2
 		exit 1;
 		;;
 esac
@@ -49,7 +49,7 @@ fi
 export WG_PORT
 
 mkdir -p "${__object:?}/files/"
-"${__type:?}/files/wireguard.conf.sh" "$private_key" > "${__object:?}/files/wg-${__object_id:?}.conf"
+"${__type:?}/files/wireguard.conf.sh" "${private_key}" > "${__object:?}/files/wg-${__object_id:?}.conf"
 
 # Wireguard configuration. Configured using a block as it is also edited by
 # cdist-type__wireguard_peer(7).
diff --git a/type/__wireguard_peer/manifest b/type/__wireguard_peer/manifest
--- a/type/__wireguard_peer/manifest
+++ b/type/__wireguard_peer/manifest
@@ -22,12 +22,12 @@
 
 os=$(cat "${__global:?}"/explorer/os)
 
-case "$os" in
+case "${os}" in
 	alpine)
 		:
 		;;
 	*)
-		echo "This type has no implementation for $os. Aborting." >&2;
+		echo "This type has no implementation for ${os}. Aborting." >&2;
 		exit 1;
 esac
 
@@ -71,9 +71,9 @@ fi
 
 
 mkdir -p "${__object:?}/files"
-"${__type:?}/files/wg-peer.sh" "$presharedkey" > "${__object:?}/files/wg-peer"
+"${__type:?}/files/wg-peer.sh" "${presharedkey}" > "${__object:?}/files/wg-peer"
 
-required="__file/etc/wireguard/$iface.conf" \
-	__block "${__object_id:?}" --file "/etc/wireguard/$iface.conf" \
+required="__file/etc/wireguard/${iface}.conf" \
+	__block "${__object_id:?}" --file "/etc/wireguard/${iface}.conf" \
 		--text - <"${__object:?}/files/wg-peer" \
-		--state "$state"
+		--state "${state}"
